### ISSUE TITLE
'NoneType' object has no attribute 'totalMileage'

### ISSUE THREAD

**Issue by Biocef** [Kask29/Domoticz-Renault-Dacia-Plugin#5]
Bonjour,
Depuis 4 jours les infos ne remontent plus et j'ai ces erreurs. Comment je pourrais corriger ça ?

Error: Dacia: Call to function 'onCommand' failed, exception details:
Error: Dacia: Traceback (most recent call last):
Error: Dacia: File "/home/pi/domoticz/plugins/Dacia/plugin.py", line 361, in onCommand
Error: Dacia: _plugin.onCommand(Unit, Command, Level, Hue)
Error: Dacia: File "/home/pi/domoticz/plugins/Dacia/plugin.py", line 133, in onCommand
Error: Dacia: loop.run_until_complete(self.onAction("update"))
Error: Dacia: File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Error: Dacia: return future.result()
Error: Dacia: File "/home/pi/domoticz/plugins/Dacia/plugin.py", line 200, in onAction
Error: Dacia: totalMileage = Cockpit.totalMileage #float
Error: Dacia: AttributeError: 'NoneType' object has no attribute 'totalMileage'

Merci d'avance.

**Comment by Biocef** [comment]
pip install renault-api==0.2.2 suivi d'un reboot et plus de souci !
